import {
  LayoutDashboard,
  Users,
  ClipboardCheck,
  Package,
  Factory,
  Activity,
  ShoppingCart,
  KanbanSquare,
  GitBranch,
  Wallet,
  Landmark,
  BarChart3,
  Settings,
} from 'lucide-react';

export const NAV_ITEMS = [
  { label: 'Dashboard', path: '/', icon: LayoutDashboard, module: 'shared' },
  { label: 'Employees', path: '/employees', icon: Users, module: 'workforce' },
  { label: 'Attendance', path: '/attendance', icon: ClipboardCheck, module: 'workforce' },
  { label: 'Materials', path: '/materials', icon: Package, module: 'inventory' },
  { label: 'Stock Orders', path: '/StockOrders', icon: Factory, module: 'Order' },
  { label: 'Kanban', path: '/kanban', icon: KanbanSquare, module: 'production' },
  { label: 'Workflow', path: '/workflow', icon: GitBranch, module: 'production' },
  { label: 'Daily Usage', path: '/daily-usage', icon: Activity, module: 'inventory' },
  { label: 'Purchase Orders', path: '/Purchase', icon: ShoppingCart, module: 'production' },
  { label: 'Wages', path: '/wages', icon: Wallet, module: 'workforce' },
  { label: 'Accounts', path: '/accounts', icon: Landmark, module: 'finance' },
  { label: 'Reports', path: '/reports', icon: BarChart3, module: 'shared' },
  { label: 'Settings', path: '/settings', icon: Settings, module: 'shared' },
];